
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class bloodbank extends javax.swing.JFrame {

    /**
     * Creates new form bloodbank
     */
    public bloodbank() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel160 = new javax.swing.JLabel();
        jLabel161 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel148.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel148.setForeground(new java.awt.Color(255, 0, 0));
        jLabel148.setText("HSTU BLOOD  BANK");
        jLabel148.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.add(jLabel148, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        jLabel149.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel149.setForeground(new java.awt.Color(0, 51, 153));
        jLabel149.setText("Introduction    ");
        jPanel14.add(jLabel149, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 147, -1, -1));

        jTextArea13.setColumns(20);
        jTextArea13.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextArea13.setRows(5);
        jTextArea13.setText("HSTU Blood Bank:\nHSTU Blood Bank is a volunteer organization where students of HSTU willingly donate \nblood. In any case of medical emergency, anyone can contact with the volunteers and \ncan ask for donating blood. This organization already has helped in saving lives of \nhundreds. It also collaborates the medical team of M. Abdur Rahim Medical College, \nDinajpur so that they can ask for blood at any emergency of patients. ");
        jScrollPane13.setViewportView(jTextArea13);

        jPanel14.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 147, 840, 150));

        jLabel150.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel150.setForeground(new java.awt.Color(0, 0, 255));
        jLabel150.setText("Treasurer");
        jPanel14.add(jLabel150, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, 50));

        jLabel151.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel151.setForeground(new java.awt.Color(0, 0, 255));
        jLabel151.setText("FaceBook Link");
        jPanel14.add(jLabel151, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, -1, -1));

        jLabel152.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel152.setForeground(new java.awt.Color(0, 0, 255));
        jLabel152.setText("General Secretary");
        jPanel14.add(jLabel152, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        jLabel153.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel153.setForeground(new java.awt.Color(0, 0, 204));
        jLabel153.setText("E-Mail");
        jPanel14.add(jLabel153, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, -1, -1));

        jLabel154.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel154.setForeground(new java.awt.Color(0, 0, 204));
        jLabel154.setText("Contact Number");
        jPanel14.add(jLabel154, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, -1, -1));

        jLabel155.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel155.setText("Mr C");
        jPanel14.add(jLabel155, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        jLabel156.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel156.setText("Mr L");
        jPanel14.add(jLabel156, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        jLabel157.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel157.setText("hstubloodbank@gmail.com");
        jPanel14.add(jLabel157, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, -1, -1));

        jLabel158.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel158.setText("fb.com/hstubloodbank");
        jPanel14.add(jLabel158, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, -1, -1));

        jLabel159.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel159.setText("01773154767 (General Purpose)");
        jPanel14.add(jLabel159, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, -1, -1));

        jButton13.setBackground(new java.awt.Color(255, 255, 51));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setText("Back To Home");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 800, 167, -1));

        jLabel160.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel160.setForeground(new java.awt.Color(0, 0, 255));
        jLabel160.setText("Contact Number");
        jPanel14.add(jLabel160, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, 50));

        jLabel161.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel161.setForeground(new java.awt.Color(0, 0, 255));
        jLabel161.setText("Vice President ");
        jPanel14.add(jLabel161, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, 50));

        jLabel162.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel162.setText("01839329378 (Treasurer)");
        jPanel14.add(jLabel162, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        jLabel163.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel163.setText("Mr D");
        jPanel14.add(jLabel163, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\OneDrive\\Documents\\Desktop\\bb.jpg")); // NOI18N
        jPanel14.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(450, 450, 450))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 1173, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bloodbank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bloodbank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bloodbank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bloodbank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bloodbank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JTextArea jTextArea13;
    // End of variables declaration//GEN-END:variables
}
